### ISSUE TITLE
[Bug] You're in Grave Danger compatibility issue

### ISSUE THREAD

**Issue by linaraincalzando** [wisp-forest/accessories#10]
When using YIGD if you have items in Accessory slots and access your grave the items in the Accessory slots will be deleted.

**Comment by Dragon-Seeker** [comment]
Do you have the Trinkets Compat layer at all?

**Comment by linaraincalzando** [comment]
Yes.

**Comment by Dragon-Seeker** [comment]
I will investigate the situation further coming up

**Comment by Dragon-Seeker** [comment]
Found a fix for the issue and will push for a fix tomorrow.

**Comment by Dragon-Seeker** [comment]
Fix should be published to modrinth fyi

**Comment by linaraincalzando** [comment]
Sorry life has been busy, just checked and not only is the error still happening, but I can no longer retrieve the YIGD inventory except for xp funnily enough.

**Comment by Dragon-Seeker** [comment]
Hmmm, send full log for better help with the issue and will quick check myself

**Comment by Dragon-Seeker** [comment]
Oddly enough I am able to get this to work with the latest version of the TC layer within a fabric specific enviroment

**Comment by linaraincalzando** [comment]
[debug.log](https://github.com/wisp-forest/accessories/files/15382383/debug.log)
[latest.log](https://github.com/wisp-forest/accessories/files/15382384/latest.log)
here are my logs oddly enough I was able to access my grave again this time even if it still deleted the trinkets and curios

**Comment by Dragon-Seeker** [comment]
~~The log file indicates that you don't have the trinkets compat layer installed and such means that the YIGD will be unable to handle the accessories slots~~ Nvm log file buried it for some reason

**Comment by Dragon-Seeker** [comment]
The referenced accessories_tclayer seems to be the old version without the fix for YIGD

**Comment by linaraincalzando** [comment]
Thats an oops on my part I dont know why I thought that only accessories and not the tclayer layer had to be updated. Checking now.

**Comment by linaraincalzando** [comment]
Yup! The issue is fixed! Thank you very much for your hard work!
