### ISSUE TITLE
Neo Forge 1.21.1 ticking entity crash 

### ISSUE THREAD

**Issue by TheeFlyingPenguin** [wisp-forest/accessories#102]
I'm not sure this mod is the problem, but the world worked fine until we faced a pillager. The moment he drew his crossbow the game crashed. I had to download neruina mod so that we can still play without crashing every time we are spotted by pillagers. I haven't stayed so much in the nether but by the time I was there hunting for some ender pearls some piglins were also crashing due tick.
I've posted one of the crash logs under: 
https://gist.github.com/a010bd490285906654b331183b63a564.git

**Comment by Dragon-Seeker** [comment]
This is an issue with [NyfsQuiver](https://www.curseforge.com/minecraft/mc-mods/nyfs-quivers) Mod as they are trying to get a capability for accessories without checking if anything was returned leading to a crash. It seems issues have been made about this within the discord already.

**Comment by Dragon-Seeker** [comment]
I am closing this as this is not the fault of Accessories and recommend reaching out the mod author to get this fixed.

**Comment by TheeFlyingPenguin** [comment]
Thanks for the time and resolve. 
Have a great day.
