### ISSUE TITLE
[Neoforge 1.21.1] Using Sodium with the Curios Compatability Layer breaks mod loading

### ISSUE THREAD

**Issue by AwesomeSavage** [wisp-forest/accessories#103]
Basically, when I try to load Sodium with this mod and the Curios Compatability, the game crashes before it loads enough to cause a crash report. I have confirmed with the Developers of Sodium that it is not an issue with Sodium, despite the logs making it look like it is.

Speaking of logs: 
[debug.log](https://github.com/user-attachments/files/16971597/debug.log)
[latest.log](https://github.com/user-attachments/files/16971598/latest.log)

To specify, I am using the versions of both mods which are on Curseforge.

**Comment by Dragon-Seeker** [comment]
Can not reproduce with just Accessories and the Curios Compat layer. I believe such is another mod within your pack and you need to [binary search](https://en.wikipedia.org/wiki/Binary_search) for the problem mods

**Comment by AwesomeSavage** [comment]
All I know is that I turned off accessiories and the modpack worked, but I'll try.

**Comment by kittywitch** [comment]
Update: nothing to do with accessories + cc layer

**Comment by Dragon-Seeker** [comment]
Closing this issue as stale, if the problem is reproducible please given more info on the mod set
