### ISSUE TITLE
Crash when Pillagers are loaded

### ISSUE THREAD

**Issue by Lunarbl00m** [wisp-forest/accessories#105]
![image](https://github.com/user-attachments/assets/4b435786-d6a8-4fa8-a288-a4ae99eb6e8e)
This is what I see before my game crashes with the accessories mod installed.

The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "io.wispforest.accessories.api.AccessoriesCapability.getFirstEquipped(net.minecraft.world.item.Item)" because the return value of "io.wispforest.accessories.api.AccessoriesCapability.get(net.minecraft.world.entity.LivingEntity)" is null

^ Thats the log I get from Minecraft Launcher.

**Comment by Dragon-Seeker** [comment]
I need the full log for such stored within `.minecraft` folder as this is not much to go off of

**Comment by Lunarbl00m** [comment]
[latest.log](https://github.com/user-attachments/files/17005009/latest.log)

**Comment by Dragon-Seeker** [comment]
This is a crash with [nyfsquiver](https://www.curseforge.com/minecraft/mc-mods/nyfs-quivers) mod and has been reported to them but nothing has been done yet to fix the issue, closing this as nothing can be done within Accessories
