### ISSUE TITLE
can support corpse?

### ISSUE THREAD

**Issue by fulide** [wisp-forest/accessories#107]
https://github.com/henkelmax/corpse

curios's item can not save in corpse when i die

**Comment by Dragon-Seeker** [comment]
As stated within this [issues](https://github.com/henkelmax/corpse/issues/133) such is an issue with curios as well and as stated with their other mod [Gravestone Issue](https://github.com/henkelmax/gravestone/issues/119) that such seems not to be planned in any way. Recommend other mods like [YIGD](https://modrinth.com/mod/yigd) as such has support for Accessories and is neoforge.
