### ISSUE TITLE
[1.20.1] Incomatibilty with Enigmatic Legacy Ring of Seven Curses

### ISSUE THREAD

**Issue by furtabs** [wisp-forest/accessories#109]
The ring pops off on death. it shouldn't be doing this.

**Comment by Dragon-Seeker** [comment]
I have a hunch why such is happening on death as I may have messed up the logic for an event after adjusting such to allow for no change though nullablity.

**Comment by Dragon-Seeker** [comment]
It should be fixed with the latest release of compat layer and accessories... I hope

**Comment by Xplodin** [comment]
It seems to also unequip the starting necklace too, the amulet

**Comment by Xplodin** [comment]
Yeah I still get this bug

**Comment by Dragon-Seeker** [comment]
):

**Comment by Dragon-Seeker** [comment]
Released [a version](https://modrinth.com/mod/accessories-cc-layer/version/7.4.0-beta.18) that I have tested and it seems to fix the issues
