### ISSUE TITLE
[1.0.0-beta35_1.20.1_Forge-47.3.10] Botania Curios Tooltips 

### ISSUE THREAD

**Issue by BookerCatch** [wisp-forest/accessories#114]
Accessories: 1.0.0-beta35
Curios Compat Layer: 7.4.0

Botania's curios will not have tooltip information displayed. On JEI, this will generate an invalid red-styled tooltip. On EMI, rendering the tooltip will crash the game. Logs suggest this is a result of invalid characters being generated for the accessorie id i.e. "botania:reach_ring" gets converted into "accessories:Reach ring"

[latest.log](https://github.com/user-attachments/files/17116742/latest.log)

**Comment by BookerCatch** [comment]
Should note downgrading to Accessories 1.0.0-Beta31 and Curios Compat Layer 7.4.0-Beta 12 resolves the issue

**Comment by Dragon-Seeker** [comment]
Should be fixed with latest release of accessories and compat layer
