### ISSUE TITLE
[1.20.1-BUG] java.lang.IllegalStateException: Unable to handle the given literal as its not a valid AttributeModifier Operation! [Literal: addition]

### ISSUE THREAD

**Issue by TeQTabanca** [wisp-forest/accessories#118]
Accessories mod crashes Minecraft if you don't have a world in Singleplayer mod

[Client Log](https://gist.github.com/TeQTabanca/46587e8960e0d82b93c88e677ea095da)

**Comment by Dragon-Seeker** [comment]
Wait are you saying if you connect to a server the client crashes as it needs to go into a singleplayer world?

**Comment by TeQTabanca** [comment]
> Wait are you saying if you connect to a server the client crashes as it needs to go into a singleplayer world?

Since there are no worlds in single player, the mod crashes Minecraft.



https://github.com/user-attachments/assets/f008d8a6-f99b-4229-aac0-2ece85ce9595

**Comment by Dragon-Seeker** [comment]
Because you are using SKLauncher I must stop assisting you and close this issue as such breaks Minecraft's TOS for Piracy, I am sorry as I recommend a launcher like prism, curseforge launcher, or even the modrinth launcher

**Comment by TeQTabanca** [comment]
> Because you are using SKLauncher I must stop assisting you and close this issue as such breaks Minecraft's TOS for Piracy, I am sorry as I recommend a launcher like prism, curseforge launcher, or even the modrinth launcher

SKlauncher has both offline and online mode. What doesn't fit into Minecraft's TOS for Piracy? Additionally, the [prism](https://tip.neiki.dev/file/6cbbfe0860d7c601d7c179840ebbf2c65009382419d539ab2d11db91c6ea1dd7) you suggested is detected as a 12.5-25% virus in [curseforge launcher](https://tip.neiki.dev/file/1c99799965731770e22ab9dd0e5f8c37192c0df4214f16a3f67856f19d7088c7) and [modrinth](https://tip.neiki.dev/file/c882b56c970ba07f80c952640783f36aff175ff4578e8a1608a239df2e952319) launchers, but it appears as a 0% virus in [SKlauncher](https://tip.neiki.dev/file/4bc59dacfa6a02b5e825ccb4d545e6749393b30783459637c5075a6c2b60bc68). Which one is safe? What I mean is that since 3rd party applications do not pay registration fees to antivirus programs, they are generally false-positive. As a result, trusted applications should be chosen, not popular (known) applications.

**Comment by Dragon-Seeker** [comment]
@TeQTabanca 

Frankly would not take such as truth of being a virus as typically when using a service like VirusTotal you need at least of 30% of the antivirus programs to detect something malicious before such is truly thought to be a virus. 

This seems more like false positives in general and no 3rd party applications can pay antivirus providers to be registered as such as safe cause that would mean anyone could pay enough money to be called safe while being a virus. I also think this website takes a bunch of other services with different scoring systems that require their own amount of scrutiny to gauge if something is a virus meaning the percentage given is kinda BS.

Prism is fully open source and can be searched while SKLauncher source is unknown and frankly quite newer compared to prism which has a long history of where it came and its current gitlog can show such.

Curseforge is a massive company so if virus or malware was containing within such it would be a huge problem on there side which I doubt as I would hope they would take the correct steps.

Modrinth launcher is also open source and can be viewed similar to prism and are a recognises company that actively attempts to correct issues when possible.

SKLauncher provides an offline mode without an account which is against TOS of Minecraft as you need an account to play with the main game or join servers where as the Launcher provides ways of bypassing cape and skins services spoofing such and acting like a premium account. Furthermore they do ASM code modifications to the game to allow for such to work they state that they do no such thing which makes me think they are lying all around.

The statement of: "As a result, trusted applications should be chosen, not popular (known) applications." is flawed as SKLauncher is unknown trust as frankly, they do a lot of work around that may not be tracked by current virus applications properly but I don't know. There are reasons to go with the popular launchers as they have been tested by others and have the backing of known people and possible open source allowing anyone to validate the code to prevent issues.

**Comment by TeQTabanca** [comment]
> @TeQTabanca
> 
> Frankly would not take such as truth of being a virus as typically when using a service like VirusTotal you need at least of 30% of the antivirus programs to detect something malicious before such is truly thought to be a virus.
> 
> This seems more like false positives in general and no 3rd party applications can pay antivirus providers to be registered as such as safe cause that would mean anyone could pay enough money to be called safe while being a virus. I also think this website takes a bunch of other services with different scoring systems that require their own amount of scrutiny to gauge if something is a virus meaning the percentage given is kinda BS.
> 
> Prism is fully open source and can be searched while SKLauncher source is unknown and frankly quite newer compared to prism which has a long history of where it came and its current gitlog can show such.
> 
> Curseforge is a massive company so if virus or malware was containing within such it would be a huge problem on there side which I doubt as I would hope they would take the correct steps.
> 
> Modrinth launcher is also open source and can be viewed similar to prism and are a recognises company that actively attempts to correct issues when possible.
> 
> SKLauncher provides an offline mode without an account which is against TOS of Minecraft as you need an account to play with the main game or join servers where as the Launcher provides ways of bypassing cape and skins services spoofing such and acting like a premium account. Furthermore they do ASM code modifications to the game to allow for such to work they state that they do no such thing which makes me think they are lying all around.
> 
> The statement of: "As a result, trusted applications should be chosen, not popular (known) applications." is flawed as SKLauncher is unknown trust as frankly, they do a lot of work around that may not be tracked by current virus applications properly but I don't know. There are reasons to go with the popular launchers as they have been tested by others and have the backing of known people and possible open source allowing anyone to validate the code to prevent issues.

"_SKLauncher provides an offline mode without an account which is against TOS of Minecraft as you need an account to play with the main game or join servers where as the Launcher provides ways of bypassing cape and skins services spoofing such and acting like a premium account. Furthermore they do ASM code modifications to the game to allow for such to work they state that they do no such thing which makes me think they are lying all around._"**I disagree with this statement. Because you cannot access premium servers in offline mode. For those who want to play offline, there is only the texture and cape changing feature, but by the client. So only myself or people with SKlauncher can see it, but they need to turn on this feature from the launcher settings, otherwise the default texture of Minecraft appears.**


https://github.com/user-attachments/assets/f6f6468c-f9b5-44eb-9c74-5215b67ed75c

**Comment by chyzman** [comment]
bro, you are not legally allowed to play minecraft without an account, non premium servers are directly against tos

**Comment by chyzman** [comment]
there is no such thing as a "premium" minecraft server. "premium" servers are just servers, the "non premium" servers you would play on are illegal

**Comment by TeQTabanca** [comment]
> there is no such thing as a "premium" minecraft server. "premium" servers are just servers, the "non premium" servers you would play on are illegal

Anyway, I won't go on too much. If it were illegal, the online-mode feature in the server.properties file would not exist at all. Which version doesn't have an online-mode feature so far? Mojang already knew that the Minecraft game would be cracked, but instead of blocking cracked Minecraft with just a few codes, they added it to the EULA illegally. Why did they add it to the EULA illegally instead of blocking cracked Minecraft with just a few codes? Because if they block cracked Minecraft, this time the developers will crack it again as an online account and distribute it to the sites for free. This will be a very bad situation for online servers. Now, most game companies make free games. Because they know that it can be cracked, and since they can't make money, they add things like battlepass, costumes, etc. to their games and sell them for money. Only games with stories are paid. The reason is that there is no online feature and they can't add the battlepass feature, so they have to sell new story modes to the players for money.

**Comment by Dragon-Seeker** [comment]
@TeQTabanca 

This will be locked and no more discussion on Mojangs actions being illegal or not. Even if a game has no direct method to prevent hacks, cracks, or anything else, it does not make it right to private the game. Offline toggle for servers are for development environment and testing when an account is not available but nothing more. 

I recommend that you do not post any more use of cracked launcher as others will not assist you with support to prevent legal ramifications.
