### ISSUE TITLE
[1.20.1-BUG] | sophisticatedbackpacks mod | Problem opening backpack with shift+right click

### ISSUE THREAD

**Issue by TeQTabanca** [wisp-forest/accessories#119]
Sometimes the Accessories mod's gui doesn't open and gives the same error a lot in the console.

```java
[23:40:06] [Server thread/ERROR] [sophisticatedbackpacks/]: Error getting backpack wrapper - Unable to find backpack at slot index 6 in "main" inventory handler
```

https://github.com/user-attachments/assets/19349a94-9688-4085-8828-c8209847ff61

**Comment by Dragon-Seeker** [comment]
Hmm it seems that the backpack is being quickly equipped from the hotbar leading to the mod having quite a fit and not liking it which should not be occurring.
