### ISSUE TITLE
[Crash] Apotheosis, Apotheosis Attributes and Placebo: Client crash during mob spawning.

### ISSUE THREAD

**Issue by Tapacywka** [wisp-forest/accessories#12]
If you take the "Apothic Boss Summoner" (skull-shaped item) and try to use it to summon a boss, it crashes.
Here is the crashlog: https://mclo.gs/949madQ.

**Comment by Noaaan** [comment]
Does this happen in a Forge only context? Just making sure, since this is present in the log:
> SINYTRA CONNECTOR IS PRESENT!
> Please verify issues are not caused by Connector before reporting them to mod authors.
> If you're unsure, file a report on Connector's issue tracker found at https://github.com/Sinytra/Connector/issues.

**Comment by Tapacywka** [comment]
> Does this happen in a Forge only context? Just making sure, since this is present in the log:
> 
> > SINYTRA CONNECTOR IS PRESENT!
> > Please verify issues are not caused by Connector before reporting them to mod authors.
> > If you're unsure, file a report on Connector's issue tracker found at https://github.com/Sinytra/Connector/issues.

No, the mod itself is a Forge mod and works fine in parallel with a working Sinytra Connector. Without Accessories mod I can use the item and summon the boss. The crash happens only after installing Accessories, TC and CC addons.

**Comment by Dragon-Seeker** [comment]
Believe such is caused by the recent changes to extend equipment slot for enchantment stuff, cooking up a fix for such coming up

**Comment by Dragon-Seeker** [comment]
Fix should be published to modrinth fyi

**Comment by Galysso** [comment]
On my side, I am now able to spawn Apotheosis bosses. Thank you :-)
