### ISSUE TITLE
[1.20.1] Nameless Trinkets unequip themselves after relogging on a server

### ISSUE THREAD

**Issue by Xplodin** [wisp-forest/accessories#123]
title. EMI caused my log to go into hundreds of MB so I cant upload it till I fix that
basically it drops / dupes nameless trinkets items on the ground if there is no space in inventory

**Comment by Dragon-Seeker** [comment]
I believe [this version](https://modrinth.com/mod/accessories-cc-layer/version/7.4.0-beta.18) should fix the issue as tested in prod
