### ISSUE TITLE
[Fabric 1.21.1]Crash when putting Traveler Backpack in Back slot (w/ Trinket Compat)

### ISSUE THREAD

**Issue by Nephillia** [wisp-forest/accessories#125]
I am not sure if this is the correct place to post this (I am posting in both places) but I am having an issue where my game crashes due to a ticking entity error whenever I try to equip Traveler's Backpack in the Back slot. The error log shows an issue between Accessories & Traveler's Backpack but I can't tell much more than that. 
Client Log:
https://mclo.gs/zY6o49z

Server Log:
https://mclo.gs/7BgHOj4

**Comment by Dragon-Seeker** [comment]
This comes down to a issues within there code using internal menu class which I assume they are doing for a reason but its something that needs to be fixed on there side as they need to instead check for a different class [`AccessoriesMenuBase`](https://github.com/wisp-forest/accessories/blob/1.21.x-ScreenExperiments/common/src/main/java/io/wispforest/accessories/menu/variants/AccessoriesMenuBase.java)

**Comment by Dragon-Seeker** [comment]
As stated within this issue, the crash has been resolved: https://github.com/Tiviacz1337/Travelers-Backpack/issues/1043
