### ISSUE TITLE
[NeoForge][1.21.1] World shows as corrupted, game crashes when attempting to make a new world.

### ISSUE THREAD

**Issue by DanL3m0n** [wisp-forest/accessories#128]
I am playing on a modified version of Craftoria (Most recent update) and am trying to swap curios for accessories so I can use a mod that only supports accessories. I have installed the curios compat layer and removed the curios mod, and there are no curios in my curios inventory, but it still fails to load. I attempted to generate a new world to see what would happen, which resulted in the game promptly crashing. Crashlog attached below.
[crash-2024-10-11_16.18.45-client.txt](https://github.com/user-attachments/files/17347511/crash-2024-10-11_16.18.45-client.txt)

**Comment by DanL3m0n** [comment]
Here is a log from that same run.
[2024-10-11-5.log.gz](https://github.com/user-attachments/files/17347568/2024-10-11-5.log.gz)

**Comment by Dragon-Seeker** [comment]
Um that log zip has not Accessories installed

**Comment by DanL3m0n** [comment]
My bad, I forgot that it stores the latest one separately.
[2024-10-11-5.log.gz](https://github.com/user-attachments/files/17347613/2024-10-11-5.log.gz)

**Comment by DanL3m0n** [comment]
This should be the right one
[2024-10-11-6.log.gz](https://github.com/user-attachments/files/17347615/2024-10-11-6.log.gz)

**Comment by Dragon-Seeker** [comment]
@DanL3m0n 
Ah it's related to FFAPI [incompat](https://github.com/Sinytra/ForgifiedFabricAPI/issues/151) with Tectonic, I believe I have a possible fix for such. This [PR](https://github.com/Sinytra/ForgifiedFabricAPI/pull/163) should fix the issue.

Here is a download for the fixed mod while I wait for the PR to get merged: https://github.com/Dragon-Seeker/ForgifiedFabricAPI/releases/tag/4.3.0%2B59440bcc19

**Comment by DanL3m0n** [comment]
It worked, Thanks!
