### ISSUE TITLE
[Fabric][1.21.1] Mobs will not drop xp/loot when backpack is equipped

### ISSUE THREAD

**Issue by travislhaspe** [wisp-forest/accessories#129]
Hi, not sure if this is an accessories issue or an incompatibility with the Inmis backpack mod. Using the latest 1.1.0-beta.4+1.21.1, as well as trinkets compat layer 3.10.0+beta.14. When I have the backpack equipped, mobs will not drop any experience or loot. Removing the backpack fixes it. Looking at the server log, there are errors when a mob is killed relating to accessories.

[server-latest.log](https://github.com/user-attachments/files/17348791/server-latest.log)
[client-latest.log](https://github.com/user-attachments/files/17348792/client-latest.log)

**Comment by Dragon-Seeker** [comment]
Ah yea this is my fault as I lacked much experience loot context and used the incorrect set for such. I will see about releasing a fix tomorrow for such

**Comment by travislhaspe** [comment]
Oh okay awesome, thank you so much!

**Comment by Dragon-Seeker** [comment]
@travislhaspe Should be fixed with the latest release of Accessories

**Comment by travislhaspe** [comment]
Just updated and confirmed, fixed. Thank you so much! 💙
