### ISSUE TITLE
[Crash] Guard Villages: client crashes while detecting a village.

### ISSUE THREAD

**Issue by Tapacywka** [wisp-forest/accessories#13]
The crash happens while you are in the village (most likely happens while mod trying to create a Guard Villager).
Here is the crashlog: https://mclo.gs/fkENCJL.

**Comment by Dragon-Seeker** [comment]
Believe such is caused by the recent changes to extend equipment slot for enchantment stuff, cooking up a fix for such coming up

**Comment by Dragon-Seeker** [comment]
Fix should be published to modrinth fyi

**Comment by Galysso** [comment]
On my side, I don't see the bug anymore. Thank you :-)
