### ISSUE TITLE
[FORGE 1.20.1] Server unequip all accessories

### ISSUE THREAD

**Issue by Skylat** [wisp-forest/accessories#130]
Whenever any player connects to the server i play, for some reason, every accessory is unequipped. It happened to me in another 2 servers i made before.

**Comment by Dragon-Seeker** [comment]
I need more info on the version of the CCLayer used, the Accessories Version combined with the latest log.

**Comment by Dragon-Seeker** [comment]
Any update on providing log files and version info

**Comment by Skylat** [comment]
Accessories cclayer is 7.4.0 beta and accessories ver is 1.0.0 beta-41

**Comment by Dragon-Seeker** [comment]
What beta version of the CCLayer exactly and can you provide a log
