### ISSUE TITLE
[1.21.1] Experimental UI Suggesstions/Fixes

### ISSUE THREAD

**Issue by JohnGoten** [wisp-forest/accessories#133]
To avoid the need to create a dozen of issue pages holding effectively the same conversation each time, I have compiled a list of changes and potential unintended behavior I observed having tested Accessories during modpack creation.
If requested I am willing to go out of my way and split this into individual pages to differ between issues and feature requests.

- NeoForge 1.21.1 Version 21.1.69
- Accessories 1.1.0-beta.7+1.21.1
- Curios Compat Layer for Accessories 9.0.12+1.21.1
- Sodium 0.6.0-beta.2+mc1.21.1
- Iris 1.8.0-beta.5+mc1.12.1

The list:

1. "Open Accessories Screen" does not run close function upon being pressed again, inconsistent with vanilla inventory screen, pressing the regular inventory hotkey does close it (my request is for the purpose of using the accessories screen as default instead and work with other inventories like the furnace, AE2 terminal etc. as well, basically using the same function as the default "E" hotkey would do)
2. Dark mode option is limited to the accessories screen only and creates far too much of a contrast to any other inventory the player may open (potential global setting that applies to vanilla containers?)
3. Unused slots are in fact not hidden although configured as such
4. Add option/toggle for the player model to follow cursor movement on screen, currently inconsistent with vanilla inventory screen
5. Pressing the unnamed button to return to the vanilla inventory screen can lead to a creative inventory tab, namely "Saved Hotbars"
6. Option for the crafting menu in the bottom right of the upper screen rather than move the main inventory to the left slightly, edited image attached
![menu_edit](https://github.com/user-attachments/assets/8257c34d-b75f-438b-b4ba-80d41b02a118)

**Comment by Noaaan** [comment]
> Dark mode option is limited to the accessories screen only

This I believe is intentional. The dark mode is added more for convenience than a catch-all solution. You should be pairing it with other mods and/or a resource pack if desirable.

**Comment by JohnGoten** [comment]
> This I believe is intentional. The dark mode is added more for convenience than a catch-all solution. You should be pairing it with other mods and/or a resource pack if desirable.

Fair enough. Certainly not too big of a deal compared to some of the other points I mentioned. Although it being a third option for those not looking to use a resource pack of sorts may still be great to have.

**Comment by Dragon-Seeker** [comment]
1. Known problem that will get solved in the future
2. As stated by Noaaan such is toggle only for Accessories Experimental Screen
3. Unknown what you are referring to with such a statement as the mode attempts to hide unused slots by mods and not slots that are currently empty
4. Known difference by unknown to when such will be changed.
5. Idk as the Creative Inventory screen is a mystical creature that will eat you up when trying to fix things so most likely just not properly consuming click when hitting the button but low or never priority
6. The main reason it is not there is that the group filters can live there when toggled

**Comment by Dragon-Seeker** [comment]
I pushed an update with most of the problems fixed. Contains the adjustment to put the crafting grid in the sidebar area when group filters are not active.
