### ISSUE TITLE
Incompatibility with 'load my chunk' mod

### ISSUE THREAD

**Issue by X-Machiavelli** [wisp-forest/accessories#135]
https://github.com/Drathonix/LoadMyChunks/issues/24#issue-2590722134

**Comment by Drathonix** [comment]
Incompatibility is caused by including Forgified-fabric as a jarjar dependency causing fabric mixins to load after LMC's. Why is FF included as a jarjar rather than declaring it as a dependency in neoforge.mods.toml?

**Comment by Dragon-Seeker** [comment]
Currently such is just a dependency required by owolib but I plan to resolve such by cutting down to FFAPI modules to only whats required which has tested to work without issues like this as FFAPI will need more updating to prevent these incompats.

**Comment by Dragon-Seeker** [comment]
An update has been pushed to reduce the use for FFAPI to the required modules within owolib that is JIJ for Neo. Should prevent this problem as such was a mistake on my part.
