### ISSUE TITLE
[1.20.1 - Forge] Corails tombstone Incompatability

### ISSUE THREAD

**Issue by Xplodin** [wisp-forest/accessories#136]
it instead drops them on the ground except for a few, like the ring of seven curses from engimatic legacy, silent gear elytra
however, nameless trinkets, artifacts, trinkets, rings of ascension, and majruszes accessories all dropped to the ground upon claiming a grave from death

**Comment by Corail31** [comment]
Accessories seems to be a mod coming from Fabric and has no idea about the 'drop' event used in Forge.
Fortunetely, it's not a mod used a lot and they prefer to claim to use some fabric grave mods instead of understanding the real problem ^^
The 'auto-equip' will be supported when this problem of 'drop' event will be solved (this part being on my side) but the last report that i got was drops not being in the grave at all.
Edit: Curio has no problem to use the 'drop' event which is not an 'optional' event, 'avoiding this event' will just make more mods incompatible with yours (using mixin to be compatible with your mod is not a solution and would bring more problems like preventing others mods to handle their 'soulbound' enchantment).

**Comment by Dragon-Seeker** [comment]
@Corail31 
> Accessories seems to be a mod coming from Fabric and has no idea about the 'drop' event used in Forge. Fortunetely, it's not a mod used a lot and they prefer to claim to use some fabric grave mods instead of understanding the real problem ^^ 

I have resolved this issue within the 1.21.1 and above version of Accessories as I had gotten the support of YIGD (Which is multiplatform) and UniversalGraves (Fabric Only) which had the benefit of equipping directly. 

I added the API event for adjusting accessories drops expecting such to be how many gravestone mods handled such but it was not true. I find the Event itself to at least be a failsafe to prevent this issue but I find it quite messy as it will just dupe it on the inventory or ground when retrieving the grave.

@Xplodin Recommend either turning on KeepInventory or use YIGD though connector for the time being. Up to you on how you want to handle this exactly as Idk when or if I will get to backport the change

**Comment by Xplodin** [comment]
> @Corail31
> 
> > Accessories seems to be a mod coming from Fabric and has no idea about the 'drop' event used in Forge. Fortunetely, it's not a mod used a lot and they prefer to claim to use some fabric grave mods instead of understanding the real problem ^^
> 
> I have resolved this issue within the 1.21.1 and above version of Accessories as I had gotten the support of YIGD (Which is multiplatform) and UniversalGraves (Fabric Only) which had the benefit of equipping directly.
> 
> I added the API event for adjusting accessories drops expecting such to be how many gravestone mods handled such but it was not true. I find the Event itself to at least be a failsafe to prevent this issue but I find it quite messy as it will just dupe it on the inventory or ground when retrieving the grave.
> 
> @Xplodin Recommend either turning on KeepInventory or use YIGD though connector for the time being. Up to you on how you want to handle this exactly as Idk when or if I will get to backport the change

Hi, I shall try YIGD, I just realized the items drop before I even get to the grave

**Comment by Dragon-Seeker** [comment]
Can confirm that Corails Tombstone works with 1.21 and above version of Accessories but will keep this open for 1.20.1 until maintenance for 1.20.1 ends

**Comment by Xplodin** [comment]
> Can confirm that Corails Tombstone works with 1.21 and above version of Accessories but will keep this open for 1.20.1 until maintenance for 1.20.1 ends

do you happen to think itll get fixed by any chance for 1.20.1?
Id love to use corails but if im forced to YIGD, that is alright

**Comment by Xplodin** [comment]
when using YIGD, it seems to cause neruina to delete the grave when killed be a mob, leaving no death waypoint or even a grave

**Comment by Dragon-Seeker** [comment]
@Xplodin A backport of this issue with Corails Tombstone has been pushed that fixes the issue for 1.20.1, use beta 42
