### ISSUE TITLE
Beta 9 for 1.21.1 crashes on fabric loader 0.16.0 and higher

### ISSUE THREAD

**Issue by Gamiseus** [wisp-forest/accessories#137]
Was working fine earlier. Modrinth just pushed beta 9 to me, game no longer starts. made test pack with just the game, this mod plus dependencies, and tested on different versions of fabric loader.  Loader 0.15.11 works, 0.16.0 and up do not, always giving me this error. Rolling back to beta 7 is working just fine.

https://pastebin.com/6KrFJDMj

**Comment by Dragon-Seeker** [comment]
Yea, I released an update version of beta 9 as the `WrapMethod` injection was not remapping so I released a silent update for the version.

**Comment by Dragon-Seeker** [comment]
@TheHitman2772 Try re downloading beta 9 from Modrinth or curseforge

**Comment by Gamiseus** [comment]
Loading fine now, thanks for the quick update!
