### ISSUE TITLE
[1.21.1][Neoforge] Slot nemue icon not changing when editing the config file 

### ISSUE THREAD

**Issue by ffuentesm** [wisp-forest/accessories#138]
I am using the experimental slot screen and the icon stays in the top right corner, covering the Apotheosis attribute icon. 
![image](https://github.com/user-attachments/assets/6253f022-a38a-470c-a0d4-bba48aa2cfcb)
![image](https://github.com/user-attachments/assets/ff82bd8a-1581-48fe-a3a3-18cddd1a4487)

I have changed the number for some different ones, to see if there is any change in the menu icon, but nothing happens.

**Comment by Dragon-Seeker** [comment]
I have tested this and it dose move, can you use `/owo-config accessories` to edit though the config screen directly. Something is bugged where the config option button will not show for some odd reason.

**Comment by Dragon-Seeker** [comment]
Ok, so I believe the issue was due to an issue on decoding of the values that leads to it breaking. I will see about getting a fix out.

**Comment by Dragon-Seeker** [comment]
Update has been pushed hopefully allowing for the values to be read
