### ISSUE TITLE
[Bug] Inmis: Compatibility with Trinkets doesn't work, no custom backpack slot.

### ISSUE THREAD

**Issue by Tapacywka** [wisp-forest/accessories#14]
Based on the description on [Modrinth](https://modrinth.com/mod/inmis), if Trinkets is installed on the client, Inmis adds a separate slot for backpacks. Accessories TC Layer doesn't seem to do that, because there is no backpack slot, but there is an additional cloak slot at the bottom of the list (Aether adds the same one at the top). I can still put the backpack in the chestplate slot and open its inventory, so the mod itself definitely works. There is no any crash-reports or regular logs. I'm using Sinytra Connector.

**Comment by Tapacywka** [comment]
Can confirm that Inmis fully works via Connector with default Trinkets mod.
![image](https://github.com/wisp-forest/accessories/assets/71761232/61759e6b-09b0-49ae-a279-50fa27324493)
![image](https://github.com/wisp-forest/accessories/assets/71761232/28748af3-09bb-4e16-9037-2db7a2d21fda)
![image](https://github.com/wisp-forest/accessories/assets/71761232/21d44a1a-e0b8-4fed-b919-0444adacb111)

**Comment by Dragon-Seeker** [comment]
I see that the givens mod use of predicate system is a bit tricky to solve as it adds on to the existing back slot, will need to investigate further

**Comment by Dragon-Seeker** [comment]
Can confirm with testing that I have fixed such a bug and will push a fix coming up today

**Comment by Dragon-Seeker** [comment]
The update has been released on modrinth.
