### ISSUE TITLE
Unable to fall down in 1.21.1

### ISSUE THREAD

**Issue by Torathion** [wisp-forest/accessories#140]
I can't move down or up a single block, because once my character hits the ground, the game crashes.

The only mods I have installed:
- Accessories 1.1.0-beta.8
- Fabric API 0.106.0
- Lavender 0.1.13
- Things 0.4.2
- Trinkets 3.10.0
- Trinkets Compat Layer for Accessories 3.10.0
- owo-lib 0.12.15

Crash log: https://mclo.gs/WVgEGjK

How to reproduce:
- Create new modpack in modrinth app (Minecraft 1.21.1, Fabric Loader 0.16.7)
- Install those mods
- Create new world
- Fall down a single block.

**Comment by Dragon-Seeker** [comment]
Update to beta 9 where a fix was pushed for errors when ticking

**Comment by Torathion** [comment]
There is no Beta 9 in my modrinth app.

![image](https://github.com/user-attachments/assets/d9ec9dfe-5386-4135-af8b-eab80b20c51f)

**Comment by Dragon-Seeker** [comment]
https://modrinth.com/mod/accessories/version/v9qbu9UZ

**Comment by Torathion** [comment]
Okay, I've downloaded Beta 10 from the website and it works, but I have still no clue why this version is not showing in the app, even after reinstalling the app and importing it from the file. But, since this isn't part of the problem (I think), I'm closing it.
