### ISSUE TITLE
Spell book Slot from Spell Engine Missing and causing crash

### ISSUE THREAD

**Issue by JediGeneralPikachu** [wisp-forest/accessories#141]
there is no slot to equip a spellbook and it causes a crash when joing some worlds
[crash-2024-10-20_15.05.55-client.txt](https://github.com/user-attachments/files/17451781/crash-2024-10-20_15.05.55-client.txt)

**Comment by Dragon-Seeker** [comment]
Ah, recent API changes to allow for some slot redirection was missing something with EntityBinding loader leading to the slot not appearing, will get a update out to fix such issue.

**Comment by samuel-odinware** [comment]
I was just about to post this same issue. Here is my [crash report](https://pastebin.com/XwTQXEuk) for additional context.

**Comment by Dragon-Seeker** [comment]
Pushed an update for the tclayer that should fix this issue

**Comment by samuel-odinware** [comment]
That fixed the issue for me. Thank you @Dragon-Seeker !

**Comment by MININT2** [comment]
sorry to bug you, but i have this same issue but for 1.20.1 which doesn't seem to have gotten this update, although unsure if it's this exactly but here is my log anyways
[crash-2024-11-04_21.07.17-server.txt](https://github.com/user-attachments/files/17626529/crash-2024-11-04_21.07.17-server.txt)
