### ISSUE TITLE
Inventory Issue

### ISSUE THREAD

**Issue by cuz0iq** [wisp-forest/accessories#147]
I use R to open my inventory (i know weird), but with the accessories mod on, this doesn’t work. If I set any other key other than R, the inventory opens, and I know it’s this mod since i’ve done a lot of trouble shooting to figure it out, and disabled all mods but accessories and the trinkets api and this issue still persists.

**Comment by Dragon-Seeker** [comment]
Can not replicate such at all nore dose it make any sense that accessories would cause a single key not to work. Please use discord for this instead if it still happens
