### ISSUE TITLE
Incompatible: Villager Hats

### ISSUE THREAD

**Issue by u0398** [wisp-forest/accessories#148]
Attempting to put a [Villager Hat](https://modrinth.com/mod/villager-hats) in the hat slot crashes the game. After restarting the client the hat is visibly worn, however when reopening the Accessories UI the game immediately crashes.

Accessories: accessories-fabric-1.1.0-beta.14+1.21.1
TC Layer: accessories_tclayer-3.10.0-beta.18+1.21.1
Villager Hats: villager-hats-1.7.2+1.21

**Comment by Dragon-Seeker** [comment]
Can you send the crash report and latest log please?

**Comment by Dragon-Seeker** [comment]
@u0398 Can not reproduce this error as stated and without a log file I will be unable to resolve this issue

**Comment by Dragon-Seeker** [comment]
Closing this issue as stale due to not receiving anymore info, please reopen if more info is provided
