### ISSUE TITLE
Simple Hats Fabric 1.21.1 (Neoforge server + Sinytra + Accessories and compat layers for trinkets and curios)

### ISSUE THREAD

**Issue by Izreaper** [wisp-forest/accessories#149]
I am on a Neoforge server using Sinytra connector with the mod, Simple Hats (Fabric 1.21.1 version along with Accessories + compat layers of curios and trinkets). I checked the config and mob loot drop was set to true, but there were no hat bags dropping after killing mobs. I tried creative mode just to get some hat bags and some hats from the item list, but when I use them (right click) they just disappear and they don't even drop with Q.

**Comment by Dragon-Seeker** [comment]
I can not reproduce this issue, have you confirmed that this dose work with trinkets instead at all?

**Comment by Izreaper** [comment]
I decided to just create a new world and it is now working. Mods that have been removed are: ForgeConfigAPIPort-v21.1.1-1.21.1-NeoForge, emi-1.1.17+1.21.1+neoforge, connectedglass-1.1.12-neoforge-mc1.21, fast-ip-ping-v1.0.5-mc1.21.1-neoforge, yeetusexperimentus-neoforge-87.0.0.

I have a feeling it was the Forge config api port
