### ISSUE TITLE
[Bug] Curios Amor Stand: Crash when placing an armor stand

### ISSUE THREAD

**Issue by Galysso** [wisp-forest/accessories#15]
The title saying it all, I just place the logs here.

- lastet.log: https://mclo.gs/4TBIh68
- crash-report: https://mclo.gs/J3nl4TF

**Comment by Dragon-Seeker** [comment]
Hmm, I will need to investigate such but Accessories has built-in ability to equip accessories to such with shifting and using the accessories open screen menu or right-clicking such.

**Comment by Galysso** [comment]
I don't know the machinery, but if my understanding of your comment is correct, I think you might be interested by the following precision:
The crash does not occur when placing an item on the armor stand. Instead, it crashes when placing the armor stand is placed on the floor.

**Comment by Dragon-Seeker** [comment]
I understand that, what I mean is that you don't need the curios armor stand mod to be able to equip accessories as the API natively has support for such. The bug encountered will need a fix but at the moment it will need to happen in the future as its kinda of problematic to fix.

**Comment by Dragon-Seeker** [comment]
I believe that I fixed the issue with such crashing though the mod seems to be broken with such clicking the armor stand doesn't seem to work. As told its not required due to the native support for this function within Accessories but it should no longer crash the game out right. Will release a fix later today

**Comment by Dragon-Seeker** [comment]
The update has been released on modrinth.

**Comment by Dragon-Seeker** [comment]
Closing this as fixed
