### ISSUE TITLE
Why is this mod makes my Minecraft cannot run?

### ISSUE THREAD

**Issue by Psychodeus** [wisp-forest/accessories#150]
So I wanted to use **Immersive lanterns** mod, and it requires txnilib mod and your mod; accessories. I run it and my minecraft can't run just stuck, no Mojang loading screen. So I exclude all except your mod, and yes it was the problem. WHY?

https://mclo.gs/ocMeK6Z

**Comment by Dragon-Seeker** [comment]
@Psychodeus You need to install owo-lib
```
oωo-lib is required to run the following mods: - Accessories (explicit dependency)  oωo-lib is a library used by most mods under the Wisp Forest domain to ease development. This is simply a convenient installer, as oωo is missing from your installation. Should you not trust it, feel free to head to the repository and download oωo yourself.  Download and install (Y/n):
```

**Comment by Psychodeus** [comment]
@Dragon-Seeker Well, it doesn't stated in the error log of my sklauncher. Anyway, it works now, thanks!
