### ISSUE TITLE
[Feature Request][Forge 1.20.1] Add option to keep all Accessories on death, similar to Curio's implementation

### ISSUE THREAD

**Issue by ACE1337x** [wisp-forest/accessories#151]
Most/all gravestone type mods currently just do not work with Accessories, spilling the accessories on the floor when dying. This would atleast allow a temporary solution until new gravestone type mods are developed to support Accessories properly.

**Comment by Dragon-Seeker** [comment]
@ACE1337x I have released a backported fix from 1.21.1 to 1.20.1 to deal with this issue with gravestone mods not capturing accessories and have tested with quarks holder totem and corails gravestone mod, please update to beta 42 for this.

**Comment by ACE1337x** [comment]
@Dragon-Seeker i can confirm that the accessories do go in the gravestone now, thank you!
