### ISSUE TITLE
[Question] How do I add more of a specific slot type in config without creating a datapack

### ISSUE THREAD

**Issue by Crazyminer34** [wisp-forest/accessories#158]
I want more belt slots because I have so many mods and I want more things on my belt
how do I get more without making a datapack

**Comment by ZestyBlaze** [comment]
without making a datapack? Probably make a custom mod that adds more slots or creates an item that gives you loads of new slots by wearing it

**Comment by Dragon-Seeker** [comment]
There is a configuration feature to adjust the amount of belt slots you get discussed [here](https://docs.wispforest.io/accessories/slot_types/#config-file) but if you want adjust what accessories go into what slot you will need to adjust the tags most likely for the given slot
