### ISSUE TITLE
[Fabric 1.21] Game crashes on start up with Trinkets Compat for Accessories installed

### ISSUE THREAD

**Issue by rottenhewie** [wisp-forest/accessories#159]
[crash-2024-11-20_05.48.50-client.txt](https://github.com/user-attachments/files/17825613/crash-2024-11-20_05.48.50-client.txt)

Game crashes immediately with Trinkets Compat Layer for Accessories installed. 
Starting the game without it (and replacing with Trinkets mod) allows the game to open so i'm unsure what else could be causing issues. 

Sorry if the mod isn't the issue, i don't know how to read crash logs

**Comment by Dragon-Seeker** [comment]
Can you try updating the Trinkets compat layer as you are using an older version that may not be compatible with the changes that occurred within Accessories lastest builds

**Comment by rottenhewie** [comment]
The issue seems to be fixed, I updated it to the version labeled for 1.21.1. Didn't know that it was compatible, sorry for the trouble.
