### ISSUE TITLE
[1.20.1] Unknown Mixin Crash

### ISSUE THREAD

**Issue by Reshy** [wisp-forest/accessories#16]
Log:  https://pastebin.com/HxWtPbr8
Crash Report:  None

Not sure what's causing the issue

**Comment by Dragon-Seeker** [comment]
I will need the full game log to help better with this issue

**Comment by Dragon-Seeker** [comment]
@Reshy Any update on getting a full log file to look over?

**Comment by Reshy** [comment]
Log:  https://pastebin.com/xSrNRgVV

**Comment by Dragon-Seeker** [comment]
With how incomplete the logs are being, all I can say is attempt to update the main mod Accessories combined with the compatibility layers for trinkets and curios

**Comment by Reshy** [comment]
> With how incomplete the logs are being, all I can say is attempt to update the main mod Accessories combined with the compatibility layers for trinkets and curios

I've already got all three at their most recent versions.

**Comment by Dragon-Seeker** [comment]
More debugging on your side is needed as I cannot gather enough information from the given logs you sent. Please respond with more information about Modpack, version information, and a full log so I can properly help you.

**Comment by Dragon-Seeker** [comment]
If you are able to get more information about the issue I am willing to debug such but until then I am closing this issue.
