### ISSUE TITLE
Helium flamingo doesn't work with the Trinket Compatibility layer

### ISSUE THREAD

**Issue by Pop000100** [wisp-forest/accessories#164]
Helium Flamingo from [Artifacts](https://modrinth.com/mod/artifacts) doesn't allow you to float in air as it should.

**Comment by Dragon-Seeker** [comment]
More info like Accessories Version, Artifacts Version, Trinkets Compat Layer Version, Minecraft version and a copy of the latest log file.

**Comment by Aesthir** [comment]
I'm running a fabric server (MC 1.21.1 with artifacts 12.0.6, things 0.4.2, trinkets 3.10.0, and TC 3.10.0b18), and have noticed the helium flamingo works just fine, but stops working when placed into an agglomeration from things. Might be related.

**Comment by Dragon-Seeker** [comment]
@Aesthir Ah yes its an issue with Accessory Nests that is fixed with this [PR](https://github.com/ochotonida/artifacts/pull/336) that should add native support for Accessories but such is different issue I assume than posted.
