### ISSUE TITLE
[Bug] Iron's Spells 'n Spellbooks Hud Not Showing Up

### ISSUE THREAD

**Issue by Danmccool** [wisp-forest/accessories#17]
When You Equip A Spellbook You Cant See What Spells You Have Equiped

Edit: You Can See You Spells When You Shift Click The Spellbook In The Curios Slot

**Comment by Dragon-Seeker** [comment]
With testing in production, it seems that the spell wheel dose now show up, an update will be pushed later today.

**Comment by Dragon-Seeker** [comment]
The update has been released on modrinth.

**Comment by Danmccool** [comment]
@Dragon-Seeker The Bug is Still Happing With The New Update

**Comment by Dragon-Seeker** [comment]
Hmmm I see that they use the Curios Event which is a problem to say the least... temporally if you hold the book and use V or the "Cast Seleect Spell" key bind it will have it show up.

**Comment by Dragon-Seeker** [comment]
Ok such should now be fixed with a update pushed to modrinth
