### ISSUE TITLE
[Forge 1.20.1] Crash with Curios Compat layer

### ISSUE THREAD

**Issue by Yoshiman5551** [wisp-forest/accessories#171]
[crash-2024-12-20_14.49.17-fml.txt](https://github.com/user-attachments/files/18214854/crash-2024-12-20_14.49.17-fml.txt)

**Comment by Dragon-Seeker** [comment]
Dose not really seem like any info to go off of here combined with no mention of Accessories or the compat layer within the crashreport

**Comment by Yoshiman5551** [comment]
Well, the thing is, I went through all of my mods and disabled them each, and the Curios Compat Layer was the one that crashed it when enabled. No other mods seemed to cause this issue.

**Comment by Dragon-Seeker** [comment]
Can you send the latest log instead of just the crash report as currently I can no find anything wrong nor any info about the layer

**Comment by Yoshiman5551** [comment]
Okay: 
[latest.log](https://github.com/user-attachments/files/18215027/latest.log)

**Comment by Dragon-Seeker** [comment]
Yea still little to go off of and I have tested the compat layer and accessories on forge before without issue so I wonder if this is caused by some mods still left within the instance as it seems more than just Curios compat and accessories...

**Comment by Yoshiman5551** [comment]
Ummm.... I'll try and figure this out later.
