### ISSUE TITLE
Acessories v1.0.0-beta42+1.20.1 cause some high TPS dues to logger not being removed

### ISSUE THREAD

**Issue by ionutsoran** [wisp-forest/accessories#174]
As you can see below the logs show that the there is logging being run on the 1.20.1 jar which kind of eats some of the TPU and it has an impact on a heavily modded server. 
If you could please have a look at it. Thank you
![image](https://github.com/user-attachments/assets/d255cc39-1d26-4d55-9693-2a9ea5354e8d)

**Comment by Dragon-Seeker** [comment]
Should be fixed with a recent release
