### ISSUE TITLE
[Bug] Crash with Relics [1.0.0-alpha.21+1.20-neoforge]

### ISSUE THREAD

**Issue by BookerCatch** [wisp-forest/accessories#18]
Opening the accessories menu while Relics and its dependency, OctoLib, are installed caused the game to crash. Please refer to the following logs to hopefully identify the issue. Thanks.

[debug.log](https://github.com/wisp-forest/accessories/files/15447769/debug.log)
[latest.log](https://github.com/wisp-forest/accessories/files/15447770/latest.log)

**Comment by Dragon-Seeker** [comment]
Figured out the problem as it was caused by a recent fix for empty groups, such fix will be rolled out later today.

**Comment by Dragon-Seeker** [comment]
The update has been released on modrinth.
