### ISSUE TITLE
[Bug] Incorrect display of spellbook slot

### ISSUE THREAD

**Issue by Xenosentry** [wisp-forest/accessories#19]
Incorrect spellbook slot display, from mods such as Wizards (RPG Series), Paladins & Priests (RPG Series) and Archers (RPG Series). MC 1.20.1 and Fabric 0.15.11
![2024-05-28 162717](https://github.com/wisp-forest/accessories/assets/135584246/bb7c81e5-b0f9-446e-bd30-5e00947dab51)

**Comment by Xenosentry** [comment]
Addendum to the above. If the book is equipped, the slot is displayed normally.
![2024-05-28 163748](https://github.com/wisp-forest/accessories/assets/135584246/41fb97b2-7fe1-422b-9c91-9478e1c7a577)

**Comment by Tapacywka** [comment]
> Though due note that due to how Spellbook sets its icon it will render as missing which could be fixed with a resource pack by placing the icon in the assets/{any_mod_id_here}/textures/gui/slot/ folder and changing the data file of the spellbooks trinkets slot definition with the change location but its justs a visual bug and should work besides that.

**Comment by Dragon-Seeker** [comment]
Visual bug that currently has no easy fix that I can think of due to how slot icons are loaded and rendered

**Comment by Dragon-Seeker** [comment]
May have a fix for such an issue that bypasses vanilla method for rendering the slot icon without to much worry for not being in the correct location

**Comment by Dragon-Seeker** [comment]
Pushed a fix for such to modrinth that should prevent the issue within the future
