### ISSUE TITLE
"Hide" function doesn't work

### ISSUE THREAD

**Issue by EfficientStinkbug** [wisp-forest/accessories#22]
On newest fabric 1.20.4, newest version of both mods

**Comment by Dragon-Seeker** [comment]
Overall don't have a clue what mechanic is being referenced with this issue. More information is needed.

**Comment by Dragon-Seeker** [comment]
Combined with the fact that both toggling rendering of accessories and hiding slots all work in production and development. If you are attempting to toggle an accessory and such does not toggle the rendering then it might be down to the rendering implementation and no hooks to check whether such should be disabled or not.
