### ISSUE TITLE
[Bug] Incompatibility between itemstages and Accessories

### ISSUE THREAD

**Issue by Galysso** [wisp-forest/accessories#26]
I am not sure whether I should expect it to work or if it is too much to ask, or even if it should be fixed at the itemstages level, but anyway I inform you of the following issue:

itemstages allows to check that you are not wearing a forbidden equipment regarding the player's stages. In case the player does not have the stage required to wear an equipment, this one is tossed when trying to put it on.

However, when the equipment is placed in a Accessories slot, itemstages does not react (probably it does not check those slots).

I did not try yet incontrol which allows to add potion effects to the players wearing an equipement depending on the player's gamestage, but it is probable that we observe the same issue.

**Comment by Dragon-Seeker** [comment]
Does such work with Curios? I can't see any compatibility that adds support for such combined with the fact that I don't believe Curios adjusts the required inventory calls to allow such behavior.

**Comment by Galysso** [comment]
I did not try, but given this issue on their github, it looks like I don't need to try :-p
[https://github.com/Darkhax-Minecraft/ItemStages/issues/71](https://github.com/Darkhax-Minecraft/ItemStages/issues/71)

**Comment by Dragon-Seeker** [comment]
Overall think this is something that needs to be handled on the end of ItemStages with adding proper API and then maybe compat if desired on their front.
