### ISSUE TITLE
[Bug] Keep Inventory Gamerule dose not prevent dropping of Accessories

### ISSUE THREAD

**Issue by No1129** [wisp-forest/accessories#27]
Items in accessories slots still drop with keep inventory on.

`  } else if (dropRule == DropRule.DEFAULT) {
            if (entity.level().getGameRules().getRule(GameRules.RULE_KEEPINVENTORY).get()) {
                dropStack = true;`
its set to true
this may be the issue

**Comment by Dragon-Seeker** [comment]
Yes, it dose seem that that logic is incorrect... whoops. Will be pushing an update for such coming up

**Comment by Dragon-Seeker** [comment]
An update was pushed to fix this issue on modrinth
