### ISSUE TITLE
[Feature] Ability to adjust accessory UI position

### ISSUE THREAD

**Issue by TheStarWorld** [wisp-forest/accessories#28]
the mod Scout adds accessories that add more slots to the inventory, when you equip a pouch the extra slots appear on top of the accessory ui which makes changing out accessories difficult
having a way to adjust the ui should help fix this sort of thing

(Forge 1.20.1, using sinytra connector and trinkets compat layer to load scout)
![image](https://github.com/wisp-forest/accessories/assets/96512249/855e93f1-155c-44f9-a350-bc9ef40f3243)

**Comment by Dragon-Seeker** [comment]
That will be quite difficult as such would require adjusting the code for rendering and layout of the slots. I could look at within the future, but frankly, this mod should have some configurable API for adjusting the layout as other screens would have similar issues.

**Comment by Dragon-Seeker** [comment]
Overall this seems like something to look into in the future but frankly blacklisting the screen is the best thing to do for now if such exists.

**Comment by Dragon-Seeker** [comment]
After think more this is something that will not happen anytime soon.

**Comment by mateus3c** [comment]
> Overall this seems like something to look into in the future but frankly blacklisting the screen is the best thing to do for now if such exists.

how can I find out what is the screen so I can blacklist it?

**Comment by Kanadeyoru** [comment]
> Overall this seems like something to look into in the future but frankly blacklisting the screen is the best thing to do for now if such exists.

how to blacklist?
