### ISSUE TITLE
[Bug] Curios Items disappear instead of being migrated

### ISSUE THREAD

**Issue by chmonyasik** [wisp-forest/accessories#29]
I know that relics / artifacts were supposed to stay or return to the inventory, but after logging into the server - the inventory for relics is empty, used:

curios-forge-5.9.1+1.20.1.jar
trinkets-3.7.2.jar

deleted, then installed:

accessories_cclayer-7.4.0-alpha.10+1.20.jar
accessories_tclayer-3.8.1-alpha.9+1.20.jar
accessories-1.0.0-alpha.22+1.20-neoforge.jar

using:

Minecraft: 1.20.1
Forge: 47.2.30

I know it's hard to check, but I'll help in any way I can, can send a whole modpack if it helps!

**Comment by Dragon-Seeker** [comment]
Hmmm odd, as I have code that should import the data properly. Will investigate such further.

**Comment by Dragon-Seeker** [comment]
Is the version of Artifacts the Forge or fabric version?

**Comment by chmonyasik** [comment]
> Is the version of Artifacts the Forge or fabric version?

neoforge curios compat and fabric trinket compat

**Comment by Dragon-Seeker** [comment]
> neoforge curios compat and fabric trinket compat

Was asking about the [Artifacts ](https://modrinth.com/mod/artifacts) mod not the compat layers

**Comment by chmonyasik** [comment]
> > neoforge curios compat and fabric trinket compat
> 
> Was asking about the [Artifacts ](https://modrinth.com/mod/artifacts) mod not the compat layers

oh sorry, replied in morning, brain didn't turn on

artifacts-forge-9.5.4.jar

**Comment by Dragon-Seeker** [comment]
Ok, then its something with the curios compat layer import method calls that are borked. Will look it such.

**Comment by chmonyasik** [comment]
*want to clarify that in the title I meant that absolutely everything that is worn in these slots - gone, not dropped or moved to the inventory.

Just in case, I'll send the names of things that may be involved and are in our modpack:

Connector-1.0.0-beta.43+1.20.1.jar
ConnectorExtras-1.10.1+1.20.1.jar
cosmeticarmorreworked-1.20.1-v1a.jar (maybe? Who knows)
moonstone-1.1.3.0.jar
mobile-trashcan-1.2.0.jar (maybe? Who knows)
spectrum-deeper-down-1.7.8.jar (works with sinytra, but its trinkets disappear when you rejoin, haven't had time to properly test with accessories, but seems like accessories fixes this)
wizards_reborn-1.20.1-0.1.4.jar
relics-1.20.1-0.6.5.1.jar
raccompat-1.20.1-0.1.2.1.jar
ramcompat-1.20.1-0.1.3.jar
arcane_abilities-0.2.3-1.20.1.jar

By the way about relics, there is no Talisman slot, it must be added manually, but in accessories not really understood how to add a slot manually, maybe it should be added somehow  by special advancement, so I apologize, this applies to the usual curios / trinkets, so not your's problem

Highlighter-1.20.1-forge-1.1.9.jar (maybe? Who knows)

Apologize for not being able to give more information, I just didn't have any log or crash log, it may be possible to test in single world, if you need - I will help you as much as I can

**Comment by Dragon-Seeker** [comment]
I have tested and found that the Curios Data conversion seems borked on my end for some odd reason. I have tested trinkets and it seems to work which is good. 

> By the way about relics, there is no Talisman slot, it must be added manually... 

Do you mean its missing within Accessories only or in Curios also? If its Accessories then I will need to investigate such.

**Comment by chmonyasik** [comment]
> Do you mean its missing within Accessories only or in Curios also? If its Accessories then I will need to investigate such.

No no, it's not your problem, and not a problem of curios / trinkets, rather a mod problem (relics -> arcane_abilities), just wanted to let you know in advance if someone will appear in the future, saying that there are no talisman slot, plus to this, want to ask, do you have plans to create a config that can be used to change the number of slots or add some slots to all players on the server? Like in Curios

**Comment by Dragon-Seeker** [comment]
Ok so I fix the original issue and pushed a update to modrinth

**Comment by Dragon-Seeker** [comment]
> No no, it's not your problem, and not a problem of curios / trinkets, rather a mod problem (relics -> arcane_abilities)...

There is a config within the mod that allows you to adjust slots based on the slot name and allows you to add more of such for quick adjustments.
