### ISSUE TITLE
Cyclic crash on world creation/loading

### ISSUE THREAD

**Issue by ghost** [wisp-forest/accessories#3]
logs https://gist.github.com/Tomat777/9fd40900036e035fe0f298a6ac6226dd

To reproduce:
1.install mods
![image](https://github.com/wisp-forest/accessories/assets/146892171/2b5190e0-4c2a-4375-a2fe-eaf26a532665)
2. Try to create world

**Comment by Dragon-Seeker** [comment]
This should be fixed with the latest version of accessories on modrinth

**Comment by ghost** [comment]
It is
