### ISSUE TITLE
[Bug] Dropping Compat within Curios causes error

### ISSUE THREAD

**Issue by linaraincalzando** [wisp-forest/accessories#30]
I don't know why or how I just know that when accessories is installed zombies don't drop experience or loot.
[latest(3).log](https://github.com/user-attachments/files/15857798/latest.3.log)
[debug.log](https://github.com/user-attachments/files/15857799/debug.log)
Here are my logs I don't know how much they will help.

**Comment by Dragon-Seeker** [comment]
I see the problem and know a fix for such that I can release coming up

**Comment by Dragon-Seeker** [comment]
Fix has been pushed to modrinth
