### ISSUE TITLE
[Issue] Baubley Heart Canisters Trinkets Version mismtach

### ISSUE THREAD

**Issue by ChosenMark** [wisp-forest/accessories#32]
Mod 'Baubley Heart Canisters' (bhc) 1.0.2 requires version 3.7.2 of mod 'Accessories Trinkets Compat Layer' (tclayer), but only the wrong versions are present: 3.8.1-alpha.11/3.8.0!

**Comment by ChosenMark** [comment]
mod author fixed this btw :)

**Comment by ChosenMark** [comment]
thanks tho

**Comment by Dragon-Seeker** [comment]
Good to hear such but this is still something I will investigate to prevent within the future as it seems like something that could be reoccurring
