### ISSUE TITLE
[1.21] Neoforge: NoClassDefFoundError LivingAttackEvent

### ISSUE THREAD

**Issue by cech12** [wisp-forest/accessories#33]
Hey, I am the developer of UsefulHats and I want to add support of this mod. Unfortunately I am getting an `NoClassDefFoundError` when I start the game.

Neoforge: 21.0.37-beta

I think that has something to do with the breaking change of Neoforge 21.0.31-beta: https://neoforged.net/news/21.0release/#damage-pipeline-rework-introduced-in-neoforge-21031-beta

error message: https://pastebin.com/6h0uJfA4

**Comment by Noaaan** [comment]
Does this happen if you remove Architechtury? The log does seem to underline that the error comes from them, not Accessories

**Comment by Dragon-Seeker** [comment]
Seems to be a arch issues as there is a github issue about it [here](https://github.com/architectury/architectury-api/issues/522)

**Comment by Dragon-Seeker** [comment]
Try using https://modrinth.com/mod/architectury-api/version/13.0.2+neoforge version of arch

**Comment by cech12** [comment]
I do not use architectury in my environment. If I uncomment this line, the crash arises:
https://github.com/cech12/UsefulHats/blob/1.21/neoforge/build.gradle#L76

**Comment by Dragon-Seeker** [comment]
REI is being pulled in meaning that Arch API will be needed which is how it is there. It may be pulled in by accessories as a dependency but idk at this moment

**Comment by Dragon-Seeker** [comment]
Will make some adjustments to the buildscript to prevent these dependency from being included within the future but including a update dependency version for such should fix the crash for the time being

**Comment by cech12** [comment]
Yep, including the architectury dependency fixed the issue. Thanks for your fast support :)

**Comment by Dragon-Seeker** [comment]
Closing this issue as solved
