### ISSUE TITLE
[1.21] Neoforge: Game crashes when tool breaks 

### ISSUE THREAD

**Issue by ffuentesm** [wisp-forest/accessories#34]
Crashlog: [crash-2024-06-26_19.27.25-client.txt](https://github.com/user-attachments/files/16006230/crash-2024-06-26_19.27.25-client.txt)
Accessories: accessories-1.0.0-beta.2+1.21-neoforge.jar
Neoforge: 21.0.39

[LivingEntity.class](https://cdn.discordapp.com/attachments/424909057086717952/1255679954125983876/LivingEntity.class?ex=667e0296&is=667cb116&hm=87358ffb7a3629eb56d543bed5ee28e175425c0005d66adae5d4da52386c91e0&)

Whenever a tool breaks, the game crashes

**Comment by Dragon-Seeker** [comment]
Very odd, will investigate such.

**Comment by Dragon-Seeker** [comment]
Seems that the naming for a invoker mixin was conflicting within the name of the method leading to it being deleted somehow which I thought not possible. Will have a fix for such shortly

**Comment by Dragon-Seeker** [comment]
Fix has been pushed to modrinth and curseforge.
