### ISSUE TITLE
Mod suggestion

### ISSUE THREAD

**Issue by ChosenMark** [wisp-forest/accessories#35]
could you please add more trinket slots to allow more mod trinkets to be used ie Botania etc? please just how the mod Not Enough Trinket Slots mod 💯

**Comment by Dragon-Seeker** [comment]
That is something that will not be tackled by accessories but can be done through the datapack method of adding slots or within the config if desired but such is left to the end user.

**Comment by ChosenMark** [comment]
how do i do that?

**Comment by Dragon-Seeker** [comment]
The config method allows you to state a slot name and the amount to increase. Both will be documented within the upcoming docs.
