### ISSUE TITLE
[BUG] I think NETS or Not Enough Trinkets Slot is not working

### ISSUE THREAD

**Issue by kusayu** [wisp-forest/accessories#36]
I have the same amount of trinkets even when using NETS, I'm in fabric 1.20.1

[NETS](https://modrinth.com/datapack/nets)

**Comment by Dragon-Seeker** [comment]
Yes I see, such an issue is down to the TCLayer not trying to resize existing Accessory slots to prevent weird issues. I'm still trying to figure out the best way to handle such for both Curios and Trinkets layer so I will revisit this coming up to find some solution to this not working

**Comment by kusayu** [comment]
Thank you for the respons, I love this mods so much, the UI is so much better than default trinkets in my opinion and I really hope this mod to be more popular on the future!

**Comment by Dragon-Seeker** [comment]
Ok got around to get such fix posted to both modrinth and curseforge.
