### ISSUE TITLE
Github Readme Outdated

### ISSUE THREAD

**Issue by AzureDoom** [wisp-forest/accessories#37]
https://github.com/wisp-forest/accessories?tab=readme-ov-file#groovy

The code for NeoForge is wrong as fg.deobf isn't used for NeoForge anymore. Just needs implementation.

A line for Multiloader should be added as well:
compileOnly "io.wispforest:accessories-common:${project.accessories_version}"

Going to open a PR for this now.

**Comment by Dragon-Seeker** [comment]
Yea the readme was most likely made before Neo changed to using fg.deobf. Will look at the PR.
