### ISSUE TITLE
[Bug] Inventory Hud+ Incompatiblity

### ISSUE THREAD

**Issue by ghost** [wisp-forest/accessories#4]
Crash on world load
https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge
log https://gist.github.com/Tomat777/bb9cd9b50165091002dcf2220414c991

**Comment by Dragon-Seeker** [comment]
Due to the mod's ARR nature, it will take some time to investigate a solution but in the meantime its going to be broken.

**Comment by Dragon-Seeker** [comment]
Seems that this crash only exists for 1.20.1 and does not directly crash on startup but instead throws a bunch of errors constantly even though not directly related to curios code.

**Comment by Dragon-Seeker** [comment]
Test on 1.20.1 and 1.21 with the latest release for CCLayer seems to be fixed
