### ISSUE TITLE
[Bug] [Forge 1.20.1] When 'keepInventory' gamerule is set to 'true', dying drops equipped accessories, but keeps everything else.

### ISSUE THREAD

**Issue by maxim0p** [wisp-forest/accessories#40]
When turning the _keepInventory_ gamerule on, equiped accessories are dropped on death, but everything else in the inventory is kept.

**VIDEO DEMONSTRATION:**  [https://streamable.com/5sd09x](https://streamable.com/5sd09x)

I am using the latest version for 1.20.1 forge **"accessories-1.0.0-alpha.24+1.20-neoforge"**

Note: I am using Forge version "47.3.3", and not NeoForge. But I tested this on NeoForge "47.1.99" and it still did the same thing.
Also using the Curios compat layer alpha 13 alongside Terra Curio
But testing this with other Curios mods, and also Trinkets still did the same thing of dropping accessories.

Unless there is a separate option/way to keep accessories on death then this seems to be a bug.

**Comment by Dragon-Seeker** [comment]
Hmmm odd, though I had fixed a similar bug but will look into why such might be occuring

**Comment by Dragon-Seeker** [comment]
I believe I found out where its going wrong and its with the Drop Event implementations for the drop event

**Comment by Dragon-Seeker** [comment]
Should be fixed with the latest release of accessories
