### ISSUE TITLE
[Bug] Old You're on Grave Danger Graves delete Inventory

### ISSUE THREAD

**Issue by PalgamingHD** [wisp-forest/accessories#41]
Graves just reset your entire inventory when trying to use them. (Using trinkets compatibility)

**Comment by Dragon-Seeker** [comment]
Please include log of your latest game and version information about accessories and grave danger

**Comment by PalgamingHD** [comment]
Nevermind, the issue was with old graves before adding accessories and trinkets compatibility it seems. It shouldn't be much of an issue with new play throughs.

**Comment by Dragon-Seeker** [comment]
Hmmm I should look into such as I thought the data conversion should work with such...

**Comment by Dragon-Seeker** [comment]
I am labeling this as solved within future releases due to the recent addition with YIGD recent 1.21 commit: https://github.com/B1n-ry/Youre-in-grave-danger/commit/43b74e3815522f2adf7eb9bbf89c2e526f447867
