### ISSUE TITLE
[Bug] [Forge 1.20.1] Curios/Trinkets with a 3D model do not appear to other players in multiplayer.

### ISSUE THREAD

**Issue by maxim0p** [wisp-forest/accessories#43]
In multiplayer, when a player equips an accessory with a visual 3D model on them, other players can't see it. 

**Video demonstration:**  [https://streamable.com/t9uzl9](https://streamable.com/t9uzl9)

In the video I'm using the [Terra Curio](https://modrinth.com/mod/terra-curio) mod alongside the Curios compat layer. 
But I have also tested this with the [Craftable Capes](https://modrinth.com/mod/craftablecapes) mod alongside the Trinkets compat layer, and in both cases, other players in multiplayer scenarios could not see the equipped accessory's model in game.

Forge Version: _47.3.3_
Minecraft Version: _1.20.1_

Accessory mods used:
_accessories-1.0.0-alpha.24+1.20-neoforge
accessories_cclayer-7.4.0-alpha.13+1.20
accessories_tclayer-3.8.1-alpha.12+1.20_

**Comment by Dragon-Seeker** [comment]
I'm wondering if this is because of #42 in some way, I am gonna release a fix for such and could you try testing again with such?

**Comment by Dragon-Seeker** [comment]
Closed as fixed
