### ISSUE TITLE
[Feature] Create Common module Jar for Mojmapping Specifically

### ISSUE THREAD

**Issue by Stein-N** [wisp-forest/accessories#44]
The common artifact isn't usable outside of Arch Loom Multiloader setups.

Vanilla Gradle or ModDevGradle can't remap the Yarn Intermediary mappings, would it be possible to ship a version with the official Mojang Mappings?

**Comment by Stein-N** [comment]
![image](https://github.com/wisp-forest/accessories/assets/128091790/c761c2a4-4896-48fe-b48e-f2f530da226a)

![image](https://github.com/wisp-forest/accessories/assets/128091790/d1467ed2-4d6c-470d-b5d7-4e3f78e090a7)

**Comment by Dragon-Seeker** [comment]
Hmm interesting issue, will investigate such possiblity
