### ISSUE TITLE
[Feature] Add Wide slot tab option instead of scrolling slots menu

### ISSUE THREAD

**Issue by ffuentesm** [wisp-forest/accessories#45]
Would be also possible to use the "wide window" format instead of the scrolling version of the menu? 
Both curios and Trinket had a version of that so that you wouldn't need to scroll down a giant list of slots, depending on the modpack
![image](https://github.com/wisp-forest/accessories/assets/44974827/42abe245-81c0-4cc1-aca0-1b2473550bce)
![image](https://github.com/wisp-forest/accessories/assets/44974827/1b8d1c7c-ecc9-463a-b1df-a860df22f26c)

So maybe use the Tabs from Accessory to work as a "filter" so that when you press them, it toggles those slots to be visualized in the menu window. 
![image](https://github.com/wisp-forest/accessories/assets/44974827/310474cd-9d05-4e35-a787-c21126a93d34)

**Comment by Dragon-Seeker** [comment]
I have stated in many areas that I will be reworking screens within the future to experiment and implement similar screens to both Curios and Trinkets but at the moment such is on hold as I deal with bug fixes and figuring out a library to handle UI as vanilla system is a pain to deal with.

**Comment by Dragon-Seeker** [comment]
Such is marked as done as of 1.1.0
