### ISSUE TITLE
[Feature]Add a commadn to add/remove accessories slot

### ISSUE THREAD

**Issue by davethemodderguy** [wisp-forest/accessories#46]
I'm designing a map and a I wan to make extra belt and head slots without the use of complicated modification like datapacks

**Comment by Dragon-Seeker** [comment]
At this moment the only option is the Datapack method which there are [wiki](https://docs.wispforest.io/accessories/home/) going over the format and test mods for both [Neoforge](https://github.com/wisp-forest/accessories/tree/1.21.x/neoforge/src/testmod) and [Fabric](https://github.com/wisp-forest/accessories/tree/1.21.x/fabric/src/testmod/resources) that can be used as an example of how to adjust slot amount that I do not think it is warranted to add commands to adjust values. Such may be revisited in the future but not now.
