### ISSUE TITLE
[Bug] Crash on forge 1.20.1 with apothic curios

### ISSUE THREAD

**Issue by OmegaRogue** [wisp-forest/accessories#47]
When Apothic curios is enabled and the curios compatibility layer is installed, the world crashes on load https://mclo.gs/6OYzzAd

**Comment by Dragon-Seeker** [comment]
@OmegaRogue Seems to be a problem with Apothic Curios as there is a similar crash occurring as talked about within this issue: https://github.com/Daripher/Apothic-Curios/issues/15

Overall the mod seems to be returning a null entity within the call which is not something to be expected and is something they will need to fix on there side.

**Comment by OmegaRogue** [comment]
> @OmegaRogue Seems to be a problem with Apothic Curios as there is a similar crash occurring as talked about within this issue: [Daripher/Apothic-Curios#15](https://github.com/Daripher/Apothic-Curios/issues/15)
> 
> Overall the mod seems to be returning a null entity within the call which is not something to be expected and is something they will need to fix on there side.

This crash only occurs for me when i have the curios compatlayer installed, not with normal curios

**Comment by Dragon-Seeker** [comment]
It may only occur with Accessories but they break the API contract by passing a null entity which is a problem. This seems like a mod that should go directly to Apothic and have a PR to support this which it seems such to be desired within numerous issues. I will keep this open but unknown on how to fix this issue.

**Comment by Dragon-Seeker** [comment]
@OmegaRogue I have attempted a fix for this and it seems to work. I can not promise that the fix will make things work out well but it should prevent crashing and hopefully work without to much issue.
