### ISSUE TITLE
[Bug] AccessoryBreak Packet unable to be sent across network

### ISSUE THREAD

**Issue by JellyBubb1e** [wisp-forest/accessories#49]
https://pastebin.com/fEsKPZ04

**Comment by Dragon-Seeker** [comment]
Hmmm not much to go off of besides some network issues sending a packet. Will need to investigate.

**Comment by Dragon-Seeker** [comment]
Ok found the problem and will get such fixed.

**Comment by Dragon-Seeker** [comment]
Fix uploaded to Modrinth and Curseforge.
