### ISSUE TITLE
[Bug] Artifact mod uses Latest Curios API Changes

### ISSUE THREAD

**Issue by ghost** [wisp-forest/accessories#5]
https://www.curseforge.com/minecraft/mc-mods/artifacts
https://www.curseforge.com/minecraft/mc-mods/emi

Does work fine with curio+trinkets+connector.

To reproduce install mods, load in world, open inventory 
![image](https://github.com/wisp-forest/accessories/assets/146892171/561c8bd3-001b-4cbb-ae12-fcf339b14e78)

log: https://gist.github.com/Tomat777/2c742dc885f303aed554dd64605d80ea

**Comment by Dragon-Seeker** [comment]
The error occurs due to Curios backport of some API changes that have yet to be included within the Compay layer. Will need some time to look into such.

**Comment by Dragon-Seeker** [comment]
Should be fixed with the latest commits, version for such being uploaded to modrinth
