### ISSUE TITLE
[Bug] Missing language key in config screen

### ISSUE THREAD

**Issue by tmaster-terrarian** [wisp-forest/accessories#55]
The translatable text key `text.autoconfig.accessories.option.clientData.disabledDefaultRenderers` has no translation in English.

![image](https://github.com/user-attachments/assets/048e1785-7ce8-4672-afaf-c8d47a383e1a)

**Comment by tmaster-terrarian** [comment]
Additional info I forgot to mention (woops)
- Accessories version is `1.0.0-beta.16+1.21`
- I am viewing this screen via the Mod Menu mod.
- I downloaded both mods from Modrinth, although that shouldn't mean much.
- My mods list only contains the Accessories mod and Mod Menu mod, no others.

**Comment by Dragon-Seeker** [comment]
Ah, will see about getting a version out with such as I need to do a hot fix anyway

**Comment by Dragon-Seeker** [comment]
Ok should be published
