### ISSUE TITLE
[1.21] [bug] When Using Accessories Trinkets Compatibility Layer Items Disappear on world save

### ISSUE THREAD

**Issue by Virusnest** [wisp-forest/accessories#57]
When loading a world items placed in trinkets slot disappear when loading a world, loading a world that was saved without the compatibility layer keeps items.

**Comment by Dragon-Seeker** [comment]
Oh, I see the problem. There was a issue within how I port the reading code that led to issues and will push a simple fix.

**Comment by Dragon-Seeker** [comment]
Uploaded a fix for such.
