### ISSUE TITLE
Artifacts mod doesnt render accessories in first person

### ISSUE THREAD

**Issue by ghost** [wisp-forest/accessories#6]
accesories: ![image](https://github.com/wisp-forest/accessories/assets/146892171/80335e6e-0ace-40c8-82d1-b89b38639420)
curio: 
![image](https://github.com/wisp-forest/accessories/assets/146892171/c8989ca3-7568-412a-846d-ac54cb7ef293)

**Comment by Dragon-Seeker** [comment]
This should be fixed with the latest release of compat layers
