### ISSUE TITLE
[Bug] Strange interactions between trinkets and fortune.

### ISSUE THREAD

**Issue by JellyBubb1e** [wisp-forest/accessories#62]
When the number of trinkets equipped increases (no matter what the effect is), they enhance the fortune enchantment of the apotheosis .

https://github.com/user-attachments/assets/d16e0b1d-3800-4072-98bc-93be467fd6a8

**Comment by JellyBubb1e** [comment]
The relevant mods are as follows: 
accessories-1.0.0-alpha.27+1.20-neoforge.jar
accessories_cclayer-7.4.0-alpha.15+1.20.jar
aether-1.20.1-1.4.2-neoforge.jar
Apotheosis-1.20.1-7.4.0.jar
ApothicAttributes-1.20.1-1.3.6.jar
ars_nouveau-1.20.1-4.12.1-all.jar
cloth-config-11.1.118-forge.jar
cumulus_menus-1.20.1-1.0.0-neoforge.jar
octolib-1.20.1-0.3.jar
open-parties-and-claims-forge-1.20.1-0.23.1.jar
Patchouli-1.20.1-84-FORGE.jar
Placebo-1.20.1-8.6.2.jar
relics-1.20.1-0.6.5.2.jar

**Comment by Dragon-Seeker** [comment]
Known issues and fix is planned by backporting the Beta 1.21 changes to 1.20.1 to fix issues and such

**Comment by JellyBubb1e** [comment]
thx!

**Comment by Dragon-Seeker** [comment]
Such a fix has been published for both 1.21 and 1.20.1
