### ISSUE TITLE
[1.21][Neoforge] Crash when clicking on mod config

### ISSUE THREAD

**Issue by ffuentesm** [wisp-forest/accessories#64]
accessories_cclayer-9.0.5-beta.3+1.21
accessories-neoforge-1.0.0-beta.21+1.21
neoforge 21.0.139
Crash Log: https://pastebin.com/RWp4R7P3

When I try to access the config options, it crashes the game

**Comment by Dragon-Seeker** [comment]
Ah breaking change within Neo... dam it

**Comment by Dragon-Seeker** [comment]
Ok uploaded such a fix on both modrinth and Curseforge.
