### ISSUE TITLE
[Bug] When I enter a world, the game crashes.

### ISSUE THREAD

**Issue by JellyBubb1e** [wisp-forest/accessories#65]
Crash Log: https://mclo.gs/CYmC1Zj
accessories-neoforge-1.0.0-beta.22+1.20.1
accessories_tclayer-3.8.1-beta.3+1.20.1
accessories_cclayer-7.4.0-beta.4+1.20.1
[eeeabsmobs-1.20.1-0.94.jar](https://modrinth.com/mod/eeeab-s-mobs/versions)

**Comment by Dragon-Seeker** [comment]
Ah, forgot one method within CuriosApi... my bad. Should be a simple fix on my part

**Comment by Dragon-Seeker** [comment]
Pushed fix for such that corrects the mistake within the beta backport
