### ISSUE TITLE
[BUG/INCOMPAT] Crash when trying to create world with Vanity Slots [Fabric 0.16.0/1.20.1]

### ISSUE THREAD

**Issue by pokesmells** [wisp-forest/accessories#68]
Install the Vanity Slots mod, and try and create or load into an existing world

https://mclo.gs/NGZnO7t

**Comment by Dragon-Seeker** [comment]
You are using alpha version of tclayer as this bug was fixed in later version

**Comment by pokesmells** [comment]
> You are using alpha version of tclayer as this bug was fixed in later version 

Ah I see, on CF I believe it automatically downloaded this version as it's labeled as release

**Comment by Dragon-Seeker** [comment]
I'll update such to prevent this issue within the future
