### ISSUE TITLE
Crash with rubidium-extra

### ISSUE THREAD

**Issue by fg1989** [wisp-forest/accessories#69]
### Version

> Forge 1.20.1-47.3.5
> Accessories Neoforge 1.0.0 Alpha 24 for 1.20 (https://www.curseforge.com/minecraft/mc-mods/accessories/files/5456983)
> Cloth Config API [Forge 1.20(.1)] v11.1.118 (https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/4973441)
> Embeddium (Rubidium) Extra [(Neo)Forge 1.20.1] v0.5.4.3 (https://www.curseforge.com/minecraft/mc-mods/rubidium-extra/files/5299719)
> Embeddium 0.3.28 (https://www.curseforge.com/minecraft/mc-mods/embeddium/files/5566632)

### Reproduction Steps

> Start the game (the game crashes on start)

### Crash Report File

> The game crashes on start but does not generate a file in the "crash-reports" folder

**Comment by Dragon-Seeker** [comment]
Exact Same issue as #67

**Comment by Dragon-Seeker** [comment]
Closing such, issue tracked by #67
