### ISSUE TITLE
[Question]  Was Accessories developed in response to TheIllusiveC4 announcing that would no longer maintain the Curious Mod? 

### ISSUE THREAD

**Issue by ffuentesm** [wisp-forest/accessories#7]

**Comment by Dragon-Seeker** [comment]
No, as it was in development before the announcement came out based on the commit history. It was mainly a desire to make a multi-loader accessories mod to unify the platforms with a single API as trinkets looked like it was having issues with maintainership. The main design of accessories is to have as much as the main code and API to be within the common side to allow for such to be easily ported to any loader if needed.

**Comment by Dragon-Seeker** [comment]
Any further questions should be asked on the discord as this is really only for issues, bugs, or feature requests possibly.
