### ISSUE TITLE
Mouse scroll bug between accessories and mouse tweaks

### ISSUE THREAD

**Issue by Hiusi** [wisp-forest/accessories#70]
When you scroll, you unequip all trinket on your mouse location

![Animation](https://github.com/user-attachments/assets/b05d52d9-3389-4bff-9921-b668abeb307a)

**Comment by Dragon-Seeker** [comment]
There is a setting within Accessories Config to tackle such problem by disabling slot scrolling as that is all I can do for such.

**Comment by Hiusi** [comment]
got it!
