### ISSUE TITLE
Crash with canary and apothiccurios 

### ISSUE THREAD

**Issue by fg1989** [wisp-forest/accessories#72]
### Version

> Forge 1.20.1-47.3.5
> Placebo-1.20.1-8.6.2 (https://www.curseforge.com/minecraft/mc-mods/placebo/files/5414631)
> ApothicAttributes-1.20.1-1.3.6 (https://www.curseforge.com/minecraft/mc-mods/apothic-attributes/files/5529789)
> Apotheosis-1.20.1-7.4.0 (https://www.curseforge.com/minecraft/mc-mods/apotheosis/files/5486368)
> ApothicCurios-1.20.1-1.0.3d (https://www.curseforge.com/minecraft/mc-mods/apothic-curios/files/5497444)
> Cloth Config API [Forge 1.20(.1)] v11.1.118 (https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/4973441)
> Accessories Neoforge 1.0.0 Beta 22 for 1.20.1 (https://www.curseforge.com/minecraft/mc-mods/accessories/files/5570403)
> Curios Compat 7.4.0 Layer Beta.6 for 1.20.1 (https://www.curseforge.com/minecraft/mc-mods/accessories-cc-layer/files/5576360)
> Canary 0.3.3 for MC 1.20.1 (https://www.curseforge.com/minecraft/mc-mods/canary/files/5089991)

### Reproduction Steps

> The game crashes after a few seconds inside a world

### Crash Report File

> https://gist.github.com/fg1989/d6ae00d47f3e0ff9ed679f995d35bb63

### Additional Information

> Game starts correctly if canary is not installed, if apothiccurios is not installed or if accessories is replaced by curios

**Comment by Dragon-Seeker** [comment]
Yea, pushed an attempted work around with some not-thought-out code. I have updated such and pushed it to modrinth and curseforge
