### ISSUE TITLE
[1.21][Neoforge] Crash when add extra slot via config

### ISSUE THREAD

**Issue by ffuentesm** [wisp-forest/accessories#77]
I tried to add some extra ring slots but that crashes the game
![image](https://github.com/user-attachments/assets/e3ba55b5-5926-4ce9-9c0c-896b881d33c4)
If I add the ring slots and I try to /reload the game, or try to join a world with that addition on the configs, the game automatically crashes.

Log:https://pastebin.com/F3muv14Y
accessories-neoforge-1.0.0-beta.25+1.21.jar 
accessories_cclayer-9.0.5-beta.5+1.21
neoforge 21.0.157

**Comment by Dragon-Seeker** [comment]
Hmmm a `StackOverflowError` Ill have to investigate cause as I never had issues within testing

**Comment by Dragon-Seeker** [comment]
Released a fix for such an issue.
