### ISSUE TITLE
[Bug] Incompatible with the Affinity mod - Endec Version Issues

### ISSUE THREAD

**Issue by Zeroawa** [wisp-forest/accessories#79]

**Comment by Dragon-Seeker** [comment]
Any info on given Accessories and Compat Version combined with the version of affinity and the log/crash log of the issue.

**Comment by Zeroawa** [comment]
[Uploading latest.log…]()

**Comment by Zeroawa** [comment]
> Any info on given Accessories and Compat Version combined with the version of affinity and the log/crash log of the issue.

[2024-08-08-1.log.gz](https://github.com/user-attachments/files/16541247/2024-08-08-1.log.gz)
[latest.log](https://github.com/user-attachments/files/16541248/latest.log)

**Comment by Dragon-Seeker** [comment]
The fix would for @gliscowo to update Endec version within the mod to deal with the incompatibility.

**Comment by Dragon-Seeker** [comment]
Closed as fixed
