### ISSUE TITLE
[Bug] Mending enchated items are not detected for Accessories

### ISSUE THREAD

**Issue by linaraincalzando** [wisp-forest/accessories#8]
Items that have mending like elytra are not being detected as having mending.

![image](https://github.com/wisp-forest/accessories/assets/99147940/cbd0fa72-a313-4043-b082-167cef4fed50)

**Comment by Dragon-Seeker** [comment]
I will need to investigate further on how to exactly deal with this problem as I can fix it specifically for mending as a patch but overall, it is going to be a problem with more than just the Mending enchantment meaning.

**Comment by Tapacywka** [comment]
I think you should first check to see if Mending works in Trinkets itself without using Accessories. If not, then you need to inform them about this problem. That way, this problem will be solved for those who do not use the Accessories mod as well. If it does work in Trinkets, then you can try to fix it in the Accessories mod.

**Comment by linaraincalzando** [comment]
> I think you should first check to see if Mending works in Trinkets itself without using Accessories. If not, then you need to inform them about this problem. That way, this problem will be solved for those who do not use the Accessories mod as well. If it does work in Trinkets, then you can try to fix it in the Accessories mod.

I would think it would be odd that Trinkets has the ability to completely nullify Curios slot mending abilities. I also was able to have my elytra mend in the trinket slot even though I am using forge elytra slot and the gloves are from the Aether mod so that is mute there. So if I am using both there doesnt seem to be an issue there. I also checked in a Fabric save and I can use the mending ability in it just fine.

**Comment by Dragon-Seeker** [comment]
Due to the Compatability layers implementing most of the needed public-facing API, the underline code to handle mending is not included. Such will need to be added to Accessories as a whole for such to work.

**Comment by Dragon-Seeker** [comment]
Released a fix for this combined with some under-the-hood changes to make many more enchantments work with accessory items that have such.

**Comment by linaraincalzando** [comment]
Looks good!
