### ISSUE TITLE
Sophisticated Backpacks GUI rendering incorrectly + Some items from Artifacts don't apply their effects.

### ISSUE THREAD

**Issue by Zimnyte** [wisp-forest/accessories#80]
**Describe the bug**
When backpack is put into the back slot using accessories mod with trinket layer combability, the GUI is not rendered properly and backpack can't be accessed. When put directly on the chest slot everything works fine.

I also noticed that some Artifacts trinkets are not working properly. For example digging claws and Running Shoes don't apply their effects to player when put in their slots. Also when switched to regular Trinkets mod everything works with no issues.

**To Reproduce**

Put backpack in the back slot (accessories with trinket layer)
Open backpack with a keybind
Backpack GUI is not rendered properly
Expected behavior
Backpack GUI should be rendered properly. You can still shift+click items into the backpack but you can't take anything out since GUI is not rendering.

**Screenshots**

https://github.com/user-attachments/assets/9560a163-b2ee-4d88-a4ba-da23a0d74b49

**Versions**
Sopthisticated Core: 0.5.109+mc1.20.1-SNAPSHOT-build.104
Sopthisticated Backpacks: 3.19.5+mc1.20.1-SNAPSHOT-build.104
Accessories: 1.0.0-beta.26+1.20.1
Accessories Trinkets Compat Layer: 3.8.1+beta.6
Artifacts Fabric: 9.5.12

**Comment by Dragon-Seeker** [comment]
The latest log for such would be helpful to better diagnose the issue going on.

**Comment by Dragon-Seeker** [comment]
Also during testing within production 1.20.1 and on the latest release I have none of the issues discussed with artifacts or sophisticated backpacks.

**Comment by Zimnyte** [comment]
Tested it further. Apparently after reinstalling mods everything seems alright. I was also testing it on server now and everything works fine. Sorry for trouble but it seems like there was no issue to begin with and I probably messed up on server-side while testing.
