### ISSUE TITLE
[Bug] Null base amount crashing if add/subtract operation occurs before such being set

### ISSUE THREAD

**Issue by Xplodin** [wisp-forest/accessories#83]
using the neo forge only version due it telling me to update to a higher version
on forge 47.2.19 with connector with the trinkets addon for accessories
https://gist.github.com/Xplodin/38dfb56832e377620c8b8cd0427ebad2
The crash happened sometimes immediately and sometimes randomly

**Comment by Dragon-Seeker** [comment]
Please update the CCLayer as it is out of date and then retest

**Comment by Xplodin** [comment]
new crash, this time its at world gen screen before getting in game
https://gist.github.com/Xplodin/6339e63342675c25b852de718d97d22c

**Comment by Dragon-Seeker** [comment]
Hmm interesting bug, seems like a simple fix for accessories side issue

**Comment by Xplodin** [comment]
I should note that I am using connector with both accessories addons for the trinkets and curios. If that helps. If you need any more info ill be glad to send more logs

**Comment by Dragon-Seeker** [comment]
Pushed a fix for such that prevents this from occurring within the future.
