### ISSUE TITLE
[Bug] Incompatibility with "Iron's Spells 'n Spellbooks" Curios Slot "Spellbook" [NeoForge 1.20.1]

### ISSUE THREAD

**Issue by iBryguy** [wisp-forest/accessories#86]
The mod **Iron's Spells 'n Spellbooks** adds a curios slot for spellbooks. But when using **Accessories** and the **Curios Compat Layer for Accessories**, the additional curios slot does not appear. I cannot tell if it is added, but not visible in the UI, or if it simply is not being added.

**Accessories** version 1.0.0 beta .26 for NeoForge
**Curios Compat Layer for Accessories** version 7.4.0 beta.10 for NeoForge
**Iron's Spells 'n Spellbooks** version 3.4.0 for NeoForge

Steps to Reproduce:
1. With Accessories, Iron's Spells 'n Spellbooks, and the Curios Compat installed, add an  Iron's spellbook to your inventory
2. With the spellbook in hand, press 'V' to equip it
3. Spellbook disappears, and is not added to Accessories UI
4. Manually checking the Accessories UI, no "Spellbook" slot is present

Additional Information: [latest.log](https://github.com/user-attachments/files/16666690/latest.log)
The log does not seem to have any useful information, but I've added it just in case there is something helpful in there that I'm not seeing.

**Comment by Dragon-Seeker** [comment]
Ah, seems like I forgot the needed Legacy Player binding required for curios. Should be a simple thing to update.

**Comment by Dragon-Seeker** [comment]
Pushed an update that fixes this issue

**Comment by WesselvanGils** [comment]
This issue seems to have resurfaced on 1.21.1
