### ISSUE TITLE
Crash with latest versions, mixin inject failed

### ISSUE THREAD

**Issue by Xplodin** [wisp-forest/accessories#88]
https://gist.github.com/Xplodin/6842e81cf9c3c26021176daa3755484b

![image](https://github.com/user-attachments/assets/712f7e45-e0c4-47cc-9a3d-98d2ddf96235)

Tried the update 7.4.0 beta 11 as well and got the same error

**Comment by Dragon-Seeker** [comment]
Update the TCLayer as it is required for this version of Accessories

**Comment by Xplodin** [comment]
that worked. ty, sorry about that

**Comment by Dragon-Seeker** [comment]
> that worked. ty, sorry about that

All is good though it may be better to join the [Discord](https://discord.gg/xrwHKktV2d) for a quicker response to these kinds of issues.
