### ISSUE TITLE
Crash - Spell Engine?

### ISSUE THREAD

**Issue by lanwoodall423** [wisp-forest/accessories#89]
1.20.1 Fabric 
accessories-fabric-1.0.0-beta.30+1.20.1
accessories_tclayer-3.8.1-beta.7+1.20.1

I installed accessories and trinkets clayer on both server and client. I was able to load into the world, view my accessories. When scrolling my hotbar I got a crash to desktop. Rejoining results in the same crash. I think I reached a weapon affected by spell engine. Tested with latest accessories and also with beta 28 and prior tclayer with the same result.
[latest.log](https://github.com/user-attachments/files/16729773/latest.log)
[crash-2024-08-23_09.59.10-client.txt](https://github.com/user-attachments/files/16729774/crash-2024-08-23_09.59.10-client.txt)

**Comment by Dragon-Seeker** [comment]
This should be fixed with the latest release of Accessories and the Compat Layer

**Comment by lanwoodall423** [comment]
[latest.log](https://github.com/user-attachments/files/16787146/latest.log)
[crash-2024-08-23_09.59.10-client.txt](https://github.com/user-attachments/files/16787147/crash-2024-08-23_09.59.10-client.txt)

**Comment by Dragon-Seeker** [comment]
Ok pushed another update for the tclayer which should fix this for sure this time
