### ISSUE TITLE
[Bug] Crash with Expanded Combat

### ISSUE THREAD

**Issue by Tapacywka** [wisp-forest/accessories#9]
The client loads, you can even enter the world, but when you try to open the inventory (any: survival, creative, from accessories mod) - crashes.
https://mclo.gs/LelKcvn

**Comment by Dragon-Seeker** [comment]
Ok will require implementing the V2 screen class to prevent such issue, will investigate further about such.

**Comment by Dragon-Seeker** [comment]
Funny enough found a bug with the IMC API for curios that was leading to such mods slots not working which I have found a fix for that will be published tomorrow

**Comment by Dragon-Seeker** [comment]
Fix should be published to modrinth fyi
