### ISSUE TITLE
[Glitch] Invisible trinkets in multiplayer

### ISSUE THREAD

**Issue by L9Tigrotto** [wisp-forest/accessories#90]
Hi, Seems like trinkets are not shown in multiplayer.

friend view:
![image](https://github.com/user-attachments/assets/b53456d1-c977-450c-a99d-e59500bd7720)

My elytra in trinket slot
![huge_2024-08-24_13 02 28](https://github.com/user-attachments/assets/2a988e06-07fa-4612-9f1c-c607e396d238)

It's also invisible while i fly around.

**Comment by Dragon-Seeker** [comment]
Can I get a log for the given instance?

**Comment by L9Tigrotto** [comment]
I don't really know how to do it since it's not a crash :P

**Comment by Noaaan** [comment]
https://fabricmc.net/wiki/player:tutorials:logs#locating_logs

**Comment by L9Tigrotto** [comment]
Thanks @Noaaan for the help.

We are using [Essential](https://modrinth.com/mod/essential) to play.
Here's my (the world host) [log](https://pastebin.com/SGsCC3CH).
Here's my friend's [log](https://pastebin.com/BjCJuv9N).

My friend can't even see his equipped trinkets in third person view (somehow only i can see trunkets).

**Comment by ToppyTopology** [comment]
im having the same issue, but capes from the craftable capes mod (which uses trinkets) do not appear in multiplayer at all, though it works in singleplayer. I have the latest mods

**Comment by Dragon-Seeker** [comment]
May be useful to test with the latest release of Accessories and Trinkets compat layer as such may fix the issues of non rendering trinkets

**Comment by L9Tigrotto** [comment]
Yes now works fine!

![image](https://github.com/user-attachments/assets/091e464f-2e66-453c-9d26-e1da9e89b0d1)
