### ISSUE TITLE
Crash on hovering the mouse over a doom stone in the end

### ISSUE THREAD

**Issue by Aesthir** [wisp-forest/accessories#99]
No idea why it crashed... all other trinkets seem ok. Here's a crash report.

https://mclo.gs/uv2mBv9

**Comment by Dragon-Seeker** [comment]
What mod adds such a item?

**Comment by Aesthir** [comment]
Oh, I'm sorry... moonfabric

https://modrinth.com/mod/moonfabric

**Comment by Dragon-Seeker** [comment]
I believe such is a simple fix and a slip up with accessories during the porting process that is allowing this issue

**Comment by Dragon-Seeker** [comment]
Fix should be pushed
